version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    container_name: shareit_db
    ports:
      - "6541:5432"
    volumes:
      - ./setup.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=share_it
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=localhost
      - DB_PORT=5432

  server:
    build: server
    image: server_image
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share_it
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  gateway:
    build: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090