CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     VARCHAR(512)                            NOT NULL,
    available       BOOLEAN                                 NOT NULL,
    owner_id        BIGINT REFERENCES users (id),
    item_request_id BIGINT,
    CONSTRAINT item_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP                               NOT NULL,
    end_time   TIMESTAMP                               NOT NULL,
    item_id    BIGINT                                  NOT NULL REFERENCES items (id),
    user_id    BIGINT                                  NOT NULL REFERENCES users (id),
    status     VARCHAR(255),
    CONSTRAINT booking_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    requestor_id BIGINT                                  NOT NULL REFERENCES users (id),
    created      TIMESTAMP                               NOT NULL,
    CONSTRAINT item_requests_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(512)                            NOT NULL,
    item_id   BIGINT                                  NOT NULL REFERENCES items (id),
    author_id BIGINT                                  NOT NULL REFERENCES users (id),
    created   TIMESTAMP                               NOT NULL,
    CONSTRAINT comments_id PRIMARY KEY (id)
);