CREATE TABLE IF NOT EXISTS USERS
(
    ID    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAME  VARCHAR(255)                            NOT NULL,
    EMAIL VARCHAR(512)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS ITEMS
(
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAME            VARCHAR(255)                            NOT NULL,
    DESCRIPTION     VARCHAR(512)                            NOT NULL,
    AVAILABLE       BOOLEAN                                 NOT NULL,
    OWNER_ID        BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOKING
(
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    START_TIME TIMESTAMP                               NOT NULL,
    END_TIME   TIMESTAMP                               NOT NULL,
    ITEM_ID    BIGINT                                  NOT NULL REFERENCES ITEMS (ID),
    USER_ID    BIGINT                                  NOT NULL REFERENCES USERS (ID),
    STATUS     VARCHAR(255),
    CONSTRAINT BOOKING_ID PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ITEM_REQUESTS
(
    ID           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRIPTION  VARCHAR(255)                            NOT NULL,
    REQUESTOR_ID BIGINT                                  NOT NULL REFERENCES USERS (ID),
    CREATED      TIMESTAMP                               NOT NULL,
    CONSTRAINT ITEM_REQUESTS_ID PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TEXT      VARCHAR(512)                            NOT NULL,
    ITEM_ID   BIGINT                                  NOT NULL REFERENCES ITEMS (ID),
    AUTHOR_ID BIGINT                                  NOT NULL REFERENCES USERS (ID),
    CREATED   TIMESTAMP                               NOT NULL,
    CONSTRAINT COMMENTS_ID PRIMARY KEY (ID)
);
